➕ Added Crane (Demo)
kivymd/KivyMD pull request #694
Opened 2020-11-27 06:55 UTC by Kulothungan16

2020-11-27 15:43 UTC, HeaTTheatR requested changes

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +                    state: "down"
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +            CraneFlyScreen:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +            CraneSleepScreen:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +            CraneEatScreen:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +    canvas:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/eat_screen.kv
> +				MDList:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/eat_screen.kv
> +				            adaptive_height: True
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/fly_screen.kv
> +				MDList:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/fly_screen.kv
> +				            adaptive_height: True
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +    		spacing: dp(10)
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +                    state: "down"
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/root_screen.kv
> +                        scr.current = "fly"
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/sleep_screen.kv
> +				            adaptive_height: True
Indentation error

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/libs/kv/sleep_screen.kv
> +				MDList:
Please add one indent

2020-11-27 15:43 UTC, HeaTTheatR commented on demos/crane/main.py
> +
Please remove one indent

2020-11-28 04:57 UTC, Kulothungan16 commented
@HeaTTheatR The Indentation Errors are created by the mixture of tabs and spaces. I fixed those ✔️

2020-11-28 18:12 UTC, merged